apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  root-password: ${MONGODB_ROOT_PASSWORD}
  username: ${MONGODB_USERNAME}
  password: ${MONGODB_PASSWORD}
  database: ${MONGODB_DATABASE}

