apiVersion: batch/v1
kind: Job
metadata:
  name: create-bucket
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: mc
          image: minio/mc
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 10
              mc alias set myminio http://minio:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY" &&
              mc mb -p myminio/$S3_BUCKET
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: S3_BUCKET
      restartPolicy: OnFailure
