apiVersion: batch/v1
kind: Job
metadata:
  name: minio-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: mc
          image: minio/mc
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 10
              mc alias set myminio http://minio:9000 "$S3_ACCESS_KEY" "$S3_SECRET_KEY"
              
              if mc ls myminio | grep -q "heli-securite-media"; then
                echo "Bucket heli-securite-media already exists"
              else
                mc mb -p myminio/heli-securite-media
                echo "Created bucket heli-securite-media"
              fi
      restartPolicy: OnFailure
