name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REPOSITORY: ${{github.repository_owner}}/monacair-website

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
          labels: ${{steps.meta.outputs.labels}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCTL_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}

      - name: Update deployment file
        run: |
          export DOCKER_REGISTRY=${{ env.DOCKER_REGISTRY }}
          export DOCKER_REPOSITORY=${{ env.DOCKER_REPOSITORY }}
          export GITHUB_SHA=${{ github.sha }}
          export PAYLOAD_SECRET=$(echo -n "${{ secrets.PAYLOAD_SECRET }}" | base64)
          export DATABASE_URI=$(echo -n "${{ secrets.DATABASE_URI }}" | base64)
          
          envsubst < kubernetes/deployment.yaml > kubernetes/deployment_updated.yaml
          envsubst < kubernetes/secrets.yaml > kubernetes/secrets_updated.yaml

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment_updated.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/secrets_updated.yaml
          kubectl rollout restart deployment/monacair-website
